CREATE TABLE IF NOT EXISTS PHONE (
ID          INTEGER PRIMARY KEY,
NUMBER        VARCHAR(12) NOT NULL,
CITY_CODE       VARCHAR(10) NOT NULL,
COUNTRY_CODE       VARCHAR(10) NOT NULL);

CREATE TABLE IF NOT EXISTS USERS (
ID          INTEGER PRIMARY KEY,
NAME        VARCHAR(64) NOT NULL,
EMAIL       VARCHAR(64) NOT NULL,
PASSWORD    VARCHAR(100) NOT NULL,
IS_ACTIVE   BOOLEAN NOT NULL,
PHONE_ID    INTEGER REFERENCES PHONE(ID));